---
kind: pipeline
type: docker
name: publish
steps:
- name: build and publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: 
      from_secret: docker_repo
    tags: 
      - latest
      - '1.0.0'
      - '1.0'
      - '1'
  # when:
  #   event:
  #     - cron
      
# - name: teams-webhook
#   image: jdamata/drone-teams
#   settings:
#     webhook: 
#       from_secret: WEBHOOK
#   when: 
#     status: 
#       - success
#       - failure
trigger:
  event:
    - push