---

kind: pipeline
type: docker
name: docker build images
platform:
  os: linux
  arch: arm64
steps:
- name: build and publish
  image: plugins/docker
  settings:
    privileged: true
    userns_mode: host
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: 
      from_secret: docker_repo
    tags: 
      - latest
  # when:
  #   event:
  #     - cron
      
# - name: teams-webhook
#   image: jdamata/drone-teams
#   settings:
#     webhook: 
#       from_secret: WEBHOOK
#   when: 
#     status: 
#       - success
#       - failure
# trigger:
#   event:
#     - push